"""ETAIQ AI Assistant — every response generated by OpenRouter with full application context."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.ai.context import AIContextBuilder, ContextBuilder
from app.ai.conversation import ConversationManager, ConversationState
from app.ai.openrouter_client import OpenRouterClient, OpenRouterClientError
from app.ai.prompts import PromptBuilder
from app.ai.schemas import AssistantRequest, AssistantResponse
from app.core.logging import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Prediction sections (UX state machine — unchanged)
# ---------------------------------------------------------------------------

_PREDICTION_SECTIONS: list[dict[str, Any]] = [
    {
        "title": "Order Details",
        "description": "Tell me about the order being placed.",
        "fields": [
            {"name": "order_size", "label": "Order size (number of items)", "unit": "items"},
            {"name": "order_value", "label": "Order value", "unit": "currency units"},
        ],
    },
    {
        "title": "Restaurant",
        "description": "Tell me about the restaurant fulfilling the order.",
        "fields": [
            {"name": "lat", "label": "Restaurant latitude", "unit": "decimal degrees"},
            {"name": "lon", "label": "Restaurant longitude", "unit": "decimal degrees"},
            {"name": "avg_rating", "label": "Restaurant average rating", "unit": "0–5 scale"},
            {"name": "prep_capacity", "label": "Restaurant preparation capacity", "unit": "orders/hour"},
        ],
    },
    {
        "title": "Drop-off Location",
        "description": "Tell me where the order is being delivered.",
        "fields": [
            {"name": "drop_lat", "label": "Drop-off latitude", "unit": "decimal degrees"},
            {"name": "drop_lon", "label": "Drop-off longitude", "unit": "decimal degrees"},
        ],
    },
    {
        "title": "Rider",
        "description": "Tell me about the rider assigned to this delivery.",
        "fields": [
            {"name": "id_rider", "label": "Rider ID", "unit": "numeric ID"},
            {"name": "lat_rider", "label": "Rider current latitude", "unit": "decimal degrees"},
            {"name": "lon_rider", "label": "Rider current longitude", "unit": "decimal degrees"},
            {"name": "completed_orders", "label": "Rider completed orders today", "unit": "orders"},
            {"name": "shift_hours", "label": "Rider shift hours worked", "unit": "hours"},
            {"name": "current_load", "label": "Rider current load", "unit": "active orders"},
        ],
    },
]

_ALL_FIELDS: list[dict[str, Any]] = [
    field for section in _PREDICTION_SECTIONS for field in section["fields"]
]

_CANCEL_WORDS = {"cancel", "restart", "exit", "quit", "never mind", "nevermind", "stop"}
_PREDICT_TRIGGERS = {"predict", "make prediction", "predict eta", "estimate eta", "start prediction", "run prediction", "new prediction"}


# ---------------------------------------------------------------------------
# Intent enum — kept for backward compatibility with existing tests
# ---------------------------------------------------------------------------

from enum import Enum  # noqa: E402


class Intent(str, Enum):
    GREETING = "greeting"
    HELP = "help"
    PREDICT = "predict"
    EXPLAIN_PREDICTION = "explain_prediction"
    FEATURE_IMPORTANCE = "feature_importance"
    MODEL_INFO = "model_info"
    DATASET_INFO = "dataset_info"
    GENERAL_CHAT = "general_chat"
    CANCEL = "cancel"
    # Legacy aliases
    PREDICTION = "predict"
    MODEL_SUMMARY = "model_info"
    SHAP_EXPLANATION = "feature_importance"
    PERFORMANCE_METRICS = "model_info"
    DATASET_SUMMARY = "dataset_info"
    COMPARE_MODELS = "model_info"
    UNKNOWN = "general_chat"


_GREETING_WORDS = {"hi", "hello", "hey", "howdy", "greetings", "good morning", "good afternoon", "good evening"}
_HELP_TRIGGERS = {"help", "what can you do", "capabilities", "commands", "what do you do", "how do you work", "options"}
_EXPLAIN_TRIGGERS = {"explain", "explain prediction", "explain latest", "explain last", "why", "why did", "what drove", "what caused"}
_FEATURE_IMPORTANCE_TRIGGERS = {"feature importance", "important features", "top features", "what features", "which features", "feature weights", "shap"}
_MODEL_TRIGGERS = {"model", "model info", "model summary", "production model", "current model", "which model", "model version", "model metrics", "model performance", "compare models", "model details", "performance", "compare"}
_DATASET_TRIGGERS = {"dataset", "data", "training data", "dataset info", "dataset summary", "how many records", "columns", "features", "target column", "summarize dataset"}


def detect_intent(message: str) -> Intent:
    """Detect user intent from a normalised message string."""
    m = message.strip().lower()
    if any(w in m for w in _CANCEL_WORDS):
        return Intent.CANCEL
    if any(t in m for t in _GREETING_WORDS):
        return Intent.GREETING
    if any(t in m for t in _HELP_TRIGGERS):
        return Intent.HELP
    if any(t in m for t in _EXPLAIN_TRIGGERS):
        return Intent.EXPLAIN_PREDICTION
    if any(t in m for t in _PREDICT_TRIGGERS):
        return Intent.PREDICT
    if any(t in m for t in _FEATURE_IMPORTANCE_TRIGGERS):
        return Intent.FEATURE_IMPORTANCE
    if any(t in m for t in _MODEL_TRIGGERS):
        return Intent.MODEL_INFO
    if any(t in m for t in _DATASET_TRIGGERS):
        return Intent.DATASET_INFO
    return Intent.GENERAL_CHAT


# ---------------------------------------------------------------------------
# ChatService — single responsibility: context → prompt → OpenRouter
# ---------------------------------------------------------------------------


class ChatService:
    """
    Build full application context, assemble a structured messages list,
    and call OpenRouter. Every response is LLM-generated — no templates.
    """

    def __init__(
        self,
        *,
        context_builder: AIContextBuilder | None = None,
        prompt_builder: PromptBuilder | None = None,
        client: OpenRouterClient | None = None,
    ) -> None:
        self._context_builder = context_builder or AIContextBuilder()
        self._prompt_builder = prompt_builder or PromptBuilder()
        self._client = client or OpenRouterClient()

    async def respond(
        self,
        *,
        user_message: str,
        history: list[dict[str, str]],
        prediction_inputs: dict[str, Any] | None = None,
        prediction_result: dict[str, Any] | None = None,
    ) -> str:
        """Build context, assemble messages, call OpenRouter, return reply."""
        context = self._context_builder.build(
            prediction_inputs=prediction_inputs,
            prediction_result=prediction_result,
        )
        messages = self._prompt_builder.build_messages(
            context=context,
            history=history,
            user_message=user_message,
        )
        try:
            return self._client.chat(messages)
        except OpenRouterClientError as exc:
            logger.warning("chat_service_llm_unavailable", error=str(exc))
            raise
        except Exception as exc:
            logger.error("chat_service_unexpected_error", error=str(exc))
            raise


# ---------------------------------------------------------------------------
# ETAIQAssistantService — orchestrates state machine + ChatService
# ---------------------------------------------------------------------------


class ETAIQAssistantService:
    """
    Conversational assistant with a guided prediction state machine.

    All natural-language responses are generated by OpenRouter via ChatService.
    The state machine handles UX flow (collecting 14 numeric fields) and then
    passes the collected inputs + prediction result back to ChatService for
    the explanation response.
    """

    def __init__(
        self,
        *,
        conversation_manager: ConversationManager | None = None,
        history_limit: int = 8,
        chat_service: ChatService | None = None,
        # Legacy parameters kept for backward compatibility with existing tests
        client: Any | None = None,
        retriever: Any | None = None,
        context_builder: Any | None = None,
    ) -> None:
        self.conversation_manager = conversation_manager or ConversationManager(history_limit=history_limit)
        self._chat_service = chat_service or ChatService()
        self._repo_root = Path(__file__).resolve().parents[3]

        # Legacy shim — tests that inject client/retriever get a sync wrapper
        self.client = client
        self.retriever = retriever
        self.context_builder = context_builder
        if client is not None or retriever is not None or context_builder is not None:
            self.handle_message = self._handle_message_legacy  # type: ignore[method-assign]

    # ------------------------------------------------------------------
    # Legacy sync shim (activated only when legacy params are injected)
    # ------------------------------------------------------------------

    def _handle_message_legacy(self, request: AssistantRequest) -> AssistantResponse:
        import json as _json
        cid = request.conversation_id or self.conversation_manager.create_conversation_id()
        context: dict[str, Any] = {}
        sources: list[str] = []
        if self.retriever is not None:
            retrieved = self.retriever.retrieve_context(request.message)
            context = retrieved.get("context", {})
            sources = retrieved.get("sources", [])
        try:
            llm = self.client
            if llm is None:
                raise RuntimeError("No client")
            prompt = f"Context:\n{_json.dumps(context, indent=2)}\n\nUser: {request.message}"
            response_text = llm.generate_text(prompt)
        except Exception:
            parts = [f"{k}: {v}" for k, v in context.items()]
            response_text = "\n".join(parts) if parts else "I couldn't generate a response right now."
        self.conversation_manager.add_turn(cid, role="user", content=request.message)
        self.conversation_manager.add_turn(cid, role="assistant", content=response_text)
        return AssistantResponse(response=response_text, sources=sources, conversation_id=cid)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    async def handle_message(self, request: AssistantRequest) -> AssistantResponse:
        """Route a user message and return an OpenRouter-generated response."""
        cid = request.conversation_id or self.conversation_manager.create_conversation_id()
        raw = request.message
        m = raw.strip().lower()
        state = self.conversation_manager.get_state(cid)
        history = self.conversation_manager.get_history(cid)

        if state in (ConversationState.PREDICTION, ConversationState.WAITING_FIELD):
            response_text = await self._handle_in_prediction(cid, m, history)
        else:
            response_text = await self._dispatch(cid, m, raw, history)

        self.conversation_manager.add_turn(cid, role="user", content=raw)
        self.conversation_manager.add_turn(cid, role="assistant", content=response_text)
        return AssistantResponse(response=response_text, sources=[], conversation_id=cid)

    # ------------------------------------------------------------------
    # State machine: inside prediction flow
    # ------------------------------------------------------------------

    async def _handle_in_prediction(self, cid: str, m: str, history: list[dict[str, str]]) -> str:
        if any(w in m for w in _CANCEL_WORDS):
            self.conversation_manager.clear_prediction_data(cid)
            self.conversation_manager.set_state(cid, ConversationState.NORMAL_CHAT)
            return "Prediction cancelled. How else can I help you?"

        # Non-numeric intent interrupts — ask to continue or cancel
        if not any(c.isdigit() or c in ".-" for c in m):
            data = self.conversation_manager.get_prediction_data(cid)
            section = _PREDICTION_SECTIONS[data.get("section_index", 0)]
            field = section["fields"][data.get("field_index", 0)]
            return (
                f"You're currently in prediction mode — I still need **{field['label']}**.\n"
                f"Enter a number to continue, or type **cancel** to exit."
            )

        return await self._collect_field(cid, m, history)

    async def _collect_field(self, cid: str, m: str, history: list[dict[str, str]]) -> str:
        data = self.conversation_manager.get_prediction_data(cid)
        section_idx: int = data.get("section_index", 0)
        field_idx: int = data.get("field_index", 0)
        collected: dict[str, float] = data.get("collected", {})
        completed_sections: list[str] = data.get("completed_sections", [])

        section = _PREDICTION_SECTIONS[section_idx]
        field = section["fields"][field_idx]

        try:
            value = float(m.strip())
        except ValueError:
            return (
                f"That doesn't look like a number. "
                f"Please enter a numerical value for **{field['label']}** "
                f"({field['unit']}), or type **cancel** to exit."
            )

        collected[field["name"]] = value
        field_idx += 1

        if field_idx < len(section["fields"]):
            data.update({"field_index": field_idx, "collected": collected})
            self.conversation_manager.set_prediction_data(cid, data)
            next_field = section["fields"][field_idx]
            return f"**{next_field['label']}** ({next_field['unit']})?"

        completed_sections.append(section["title"])
        section_idx += 1

        if section_idx < len(_PREDICTION_SECTIONS):
            next_section = _PREDICTION_SECTIONS[section_idx]
            data.update({"section_index": section_idx, "field_index": 0, "collected": collected, "completed_sections": completed_sections})
            self.conversation_manager.set_prediction_data(cid, data)
            return self._section_transition(completed_sections, next_section)

        self.conversation_manager.clear_prediction_data(cid)
        self.conversation_manager.set_state(cid, ConversationState.NORMAL_CHAT)
        return await self._run_prediction_and_explain(collected, completed_sections, history)

    def _section_transition(self, completed_sections: list[str], next_section: dict[str, Any]) -> str:
        done_lines = "\n".join(f"  ✓ {s}" for s in completed_sections)
        first_field = next_section["fields"][0]
        return (
            f"**Progress**\n{done_lines}\n\n"
            f"**Next: {next_section['title']}** ({len(next_section['fields'])} fields)\n"
            f"_{next_section['description']}_\n\n"
            f"**{first_field['label']}** ({first_field['unit']})?"
        )

    # ------------------------------------------------------------------
    # Prediction execution — runs model then asks OpenRouter to explain
    # ------------------------------------------------------------------

    async def _run_prediction_and_explain(
        self,
        features: dict[str, float],
        completed_sections: list[str],
        history: list[dict[str, str]],
    ) -> str:
        done_lines = "\n".join(f"  ✓ {s}" for s in completed_sections)

        try:
            import pandas as pd
            from app.api.models import registry_engine
            from ml.training.prediction_pipeline import PredictionPipelineEngine

            production_model = registry_engine.select_production_model("XGBRegressor")
            pipeline = PredictionPipelineEngine(logger=None)
            result = pipeline.predict(production_model.artifact_path, pd.DataFrame([features]))
            eta = float(result.predictions[0])
        except Exception as exc:
            logger.error("assistant_run_prediction_failed", error=str(exc))
            return (
                f"**Progress**\n{done_lines}\n\n"
                "I collected all the values but couldn't run the prediction right now. "
                "Please try again or use the dashboard."
            )

        prediction_result = {
            "predicted_eta_minutes": eta,
            "model_name": getattr(production_model, "model_name", "XGBRegressor"),
            "model_version": getattr(production_model, "version", "unknown"),
        }

        user_message = (
            f"A delivery ETA prediction has just been completed. "
            f"The predicted ETA is {eta:.1f} minutes. "
            f"The input features used were: {features}. "
            f"Please explain this prediction to a logistics manager: "
            f"what drove this ETA, what the confidence level is, what the risk level is, "
            f"and any operational recommendations."
        )

        try:
            explanation = await self._chat_service.respond(
                user_message=user_message,
                history=history,
                prediction_inputs=features,
                prediction_result=prediction_result,
            )
        except Exception as exc:
            logger.warning("assistant_explain_after_prediction_failed", error=str(exc))
            explanation = (
                f"The model predicted an ETA of **{eta:.1f} minutes**. "
                "A detailed explanation is unavailable right now — the LLM service could not be reached."
            )

        return (
            f"**Progress**\n{done_lines}\n\n"
            f"---\n\n"
            f"**Prediction Complete** ✓\n\n"
            f"**Predicted ETA:** {eta:.1f} minutes\n\n"
            f"---\n\n"
            f"{explanation}\n\n"
            f"---\n"
            f"**You can also ask:**\n"
            f"• Show feature importance\n"
            f"• Explain latest prediction\n"
            f"• Predict another ETA"
        )

    # ------------------------------------------------------------------
    # Normal chat dispatch — all paths go through ChatService
    # ------------------------------------------------------------------

    async def _dispatch(self, cid: str, m: str, raw: str, history: list[dict[str, str]]) -> str:
        if any(t in m for t in _PREDICT_TRIGGERS):
            return self._start_prediction(cid)

        # Provide latest prediction value as context hint for explain intents
        prediction_inputs = None
        prediction_result = None
        latest_eta = self._get_latest_prediction()
        if latest_eta is not None:
            prediction_result = {"mean_prediction_minutes": latest_eta}

        try:
            return await self._chat_service.respond(
                user_message=raw,
                history=history,
                prediction_inputs=prediction_inputs,
                prediction_result=prediction_result,
            )
        except OpenRouterClientError as exc:
            logger.warning("assistant_llm_unavailable", error=str(exc))
            # Fallback: surface the latest prediction value if available
            if latest_eta is not None:
                return (
                    f"The latest predicted ETA is **{latest_eta:.2f} minutes**. "
                    "A detailed explanation is unavailable — the AI service could not be reached. "
                    "Please check that OPENROUTER_API_KEY is configured."
                )
            return (
                "The AI service is currently unavailable. "
                "Please check that OPENROUTER_API_KEY is configured and try again."
            )
        except Exception as exc:
            logger.error("assistant_dispatch_error", error=str(exc))
            return "Something went wrong. Please try again."

    def _start_prediction(self, cid: str) -> str:
        total_fields = sum(len(s["fields"]) for s in _PREDICTION_SECTIONS)
        first_section = _PREDICTION_SECTIONS[0]
        first_field = first_section["fields"][0]
        self.conversation_manager.set_state(cid, ConversationState.PREDICTION)
        self.conversation_manager.set_prediction_data(
            cid,
            {"section_index": 0, "field_index": 0, "collected": {}, "completed_sections": []},
        )
        return (
            f"Let's predict the ETA! I'll guide you through "
            f"{len(_PREDICTION_SECTIONS)} sections ({total_fields} values total).\n\n"
            f"**Section 1 of {len(_PREDICTION_SECTIONS)}: {first_section['title']}**\n"
            f"_{first_section['description']}_\n\n"
            f"**{first_field['label']}** ({first_field['unit']})?\n\n"
            f"_(Type **cancel** at any time to exit.)_"
        )

    def _get_latest_prediction(self) -> float | None:
        """Return the latest mean prediction from monitoring records."""
        try:
            from ml.training.monitoring import MonitoringEngine
            engine = MonitoringEngine(load_existing_records=True)
            record = engine.get_latest()
            if record is not None:
                return record.mean_prediction
        except Exception as exc:
            logger.warning("assistant_monitoring_read_failed", error=str(exc))
        return None

    # ------------------------------------------------------------------
    # Backward-compatible intent detection (used by existing tests)
    # ------------------------------------------------------------------

    def _detect_intent(self, message: str) -> Intent:
        """Kept for backward compatibility — delegates to module-level detect_intent."""
        return detect_intent(message)
